version: '3.8'

services:
  backend:
    build: 
      context: .
      dockerfile: Dockerfile
    command: /bin/sh ./run_server.sh
    depends_on:
      - db-postgres
    volumes:
      - .:/app
    ports:
      - "8001:8001"
    environment:
      - POSTGRES_URI = ${POSTGRES_URI}
      - DOCKERHUB_USERNAME=${DOCKERHUB_USERNAME}
      - DOCKERHUB_ACCESS_TOKEN=${DOCKERHUB_ACCESS_TOKEN}
      - MOVIEGLU_CLIENT=${MOVIEGLU_CLIENT}
      - MOVIEGLU_API_KEY=${MOVIEGLU_API_KEY}
      - MOVIEGLU_AUTHORIZATION=${MOVIEGLU_AUTHORIZATION}
      - MOVIEGLU_TERRITORY=${MOVIEGLU_TERRITORY}
      - MOVIEGLU_API_VERSION=${MOVIEGLU_API_VERSION}
      - MOVIEGLU_GEOLOCATION=${MOVIEGLU_GEOLOCATION}
      - TMDB_TOKEN=${TMDB_TOKEN}
    networks:
      - match_and_watch
  db-postgres:
    image: postgres:15-alpine
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ms-user
    networks:
      - match_and_watch
  
volumes:
  postgres-data:

networks:
  match_and_watch:
    external: true
