import http from 'k6/http';
import { sleep } from 'k6';

export const options = {
  scenarios: {
    browse: {
        executor: 'ramping-vus',
        startVUs: 0,
        stages: [
            { duration: '10s', target: 5 },
            { duration: '10s', target: 10 },
            { duration: '10s', target: 0 },
        ],
        tags: { test_type: 'history' }, // extra tags for the metrics generated by this scenario
        exec: 'historytest', // the function this scenario will execute
    },
    upload: {
        executor: 'ramping-vus',
        startVUs: 0,
        stages: [
            { duration: '10s', target: 5 },
            { duration: '10s', target: 10 },
            { duration: '10s', target: 0 },
        ],
        tags: { test_type: 'movies' }, // different extra metric tags for this scenario
        exec: 'moviestest', // this scenario is executing different code than the one above!
    },
  },
  discardResponseBodies: true,
  thresholds: {
    'http_req_duration{test_type:history}': ['p(95)<2000', 'p(99)<3000'],
    'http_req_duration{test_type:movies}': ['p(99)<10000'],
  },
};

let dict = {
  "genres": [
    "war"
  ],
  "emotions": [
    "Tension"
  ],
  "length": "long",
  "type": "movie",
  "age_certification": "+16",
  "release_year": 2010
}

let token = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJzdHJpbmciLCJpZCI6IjQ4NWJmMGU1LWMxMjEtNGNkNy1iZmZmLTQxYzY3NGIxZGFkNCIsIm5hbWUiOiJzdHJpbmciLCJzdXJuYW1lIjoic3RyaW5nIiwiZXhwIjoxNzIxODU4MDk1LjgwNzAwMX0.2YUFiR1oo0RjrkhvXcphgXqBc-iy0fTGSP4fWR-Y9Ok";


export function historytest() {
    let url = 'http://10.100.32.27:8002/api/movies/history?token=';
    url = url + token;
    http.get(url);
    sleep(1);
}

export function moviestest() {
    let url = 'http://10.100.32.27:8002/api/movies?token=';
    url = url + token;
    http.post(url, dict);
    sleep(1);
}
