"""empty message

Revision ID: 086813f46fc9
Revises: eea2fc6b4363
Create Date: 2024-07-22 19:31:01.611545

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '086813f46fc9'
down_revision: Union[str, None] = 'eea2fc6b4363'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('solo_suggestions_history', sa.Column('query_dict', sa.JSON(), nullable=True))
    op.drop_column('solo_suggestions_history', 'query_string')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('solo_suggestions_history', sa.Column('query_string', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('solo_suggestions_history', 'query_dict')
    # ### end Alembic commands ###
