"""empty message

Revision ID: 08bfe0d2d9c8
Revises: 26db73b0a131
Create Date: 2024-07-22 04:18:26.733100

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '08bfe0d2d9c8'
down_revision: Union[str, None] = '26db73b0a131'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('solo_suggestions_history', 'suggestions')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('solo_suggestions_history', sa.Column('suggestions', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
