"""empty message

Revision ID: 9ad235195ce4
Revises: 08bfe0d2d9c8
Create Date: 2024-07-22 04:55:22.901651

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9ad235195ce4'
down_revision: Union[str, None] = '08bfe0d2d9c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('solo_suggestions_history', sa.Column('description', sa.String(length=100000), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('solo_suggestions_history', 'description')
    # ### end Alembic commands ###
