"""empty message

Revision ID: d41de0dd0298
Revises: b4703b162558
Create Date: 2024-07-22 10:05:59.867736

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd41de0dd0298'
down_revision: Union[str, None] = 'b4703b162558'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('solo_suggestions_history', sa.Column('query_dict', sa.JSON(), nullable=True))
    op.drop_column('solo_suggestions_history', 'query_string')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('solo_suggestions_history', sa.Column('query_string', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('solo_suggestions_history', 'query_dict')
    # ### end Alembic commands ###
