"""empty message

Revision ID: eea2fc6b4363
Revises: d41de0dd0298
Create Date: 2024-07-22 19:27:08.210837

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'eea2fc6b4363'
down_revision: Union[str, None] = 'd41de0dd0298'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('solo_suggestions_history', sa.Column('query_string', sa.String(), nullable=True))
    op.add_column('solo_suggestions_history', sa.Column('movie_imdb_id', sa.String(length=255), nullable=True))
    op.add_column('solo_suggestions_history', sa.Column('rating', sa.Integer(), nullable=True))
    op.add_column('solo_suggestions_history', sa.Column('description', sa.String(length=100000), nullable=True))
    op.create_index(op.f('ix_solo_suggestions_history_movie_imdb_id'), 'solo_suggestions_history', ['movie_imdb_id'], unique=False)
    op.create_foreign_key(None, 'solo_suggestions_history', 'movies', ['movie_imdb_id'], ['imdb_id'])
    op.drop_column('solo_suggestions_history', 'query_dict')
    op.drop_column('solo_suggestions_history', 'suggestions')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('solo_suggestions_history', sa.Column('suggestions', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True))
    op.add_column('solo_suggestions_history', sa.Column('query_dict', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'solo_suggestions_history', type_='foreignkey')
    op.drop_index(op.f('ix_solo_suggestions_history_movie_imdb_id'), table_name='solo_suggestions_history')
    op.drop_column('solo_suggestions_history', 'description')
    op.drop_column('solo_suggestions_history', 'rating')
    op.drop_column('solo_suggestions_history', 'movie_imdb_id')
    op.drop_column('solo_suggestions_history', 'query_string')
    # ### end Alembic commands ###
